### PR TITLE
Add installation steps for logging and systemd

### PR DESCRIPTION
**Pull request by Falcosc**
@nikp123 I did not add it to the make file because I'm not sure how common systemd is.

Should the be part of make install?

### CODE REVIEW

**Review by nikp123 — COMMENTED** [review]
I'd rather leave for the user to decide which logging daemon they should use instead of doing an rsyslog.d thing. I mean systemD comes with logging functionality by default with ``systemctl status``

Change this to sound more generic and offer ``rsyslog.d`` as one of the possible ways to achieve logging

**Comment by Falcosc** [comment]
Journalctl is cool, but if you only want to spare 200-300MB for the Journalfiles, you can't save much. I was surprised how much junk gets produced in a single day after some reboots of an empty system.

After some testing I decided to avoid configuring Journals or syslogs to be persistent. So rsyslog was the simplest way to add long time logging to the project without wasting too much space.

**Comment by nikp123** [comment]
Yeah that makes sense. Be sure to add that to the documentation as well, I mean I run most of my stuff in docker atm so I've never hit such a blockade in file loggging, though I assume that rsyslog compresses the output which helps it not waste "200-300MB of journal files" as you say.

I wanted you to include ```systemctl status``` as I wasn't aware of your reasoning, but which now seems perfectly valid.

**Comment by nikp123** [comment]
unrelated: when its 12pm i can barely do english it seems

**Comment by Falcosc** [comment]
rsyslog was not used to compress anything. It's just used to persisting only things you need. I don't need to store 50mb of daily journal or syslog junk. I just want to persist my daily 10kb of wakeonlan reasons :)

**Comment by Falcosc** [comment]
What do you think about including systemctl into the make file?

And what do you think about using sudo in the documentation instead of writing  (as root) behind each command which (dependending on the system) may need root.

I don't know anything about documentation targeted for all kinds of linux systems.

**Comment by nikp123** [comment]
yeah true, i was just trying to avoid one of those (use this thing instead of that thing situations)

but yeah regardless I like your addition I just wasn't aware of the reason

**Comment by nikp123** [comment]
seems ok

**Pull request merged**
