### PR TITLE
Functional Bugfixes: broken config and broken error message

### PR DESCRIPTION
**Pull request by Falcosc**
argument parsing error message did miss the name

allow_gateway = true did not work if used inside the config file

### CODE REVIEW

**Comment by Falcosc** [comment]
@nikp123 My compiler cannot generate warnings for my test deletion of the  `m.allow_gateway_s = NULL;` statement.
I don't know what is happening.
Warning is not working: `-Wall` should enable `-Wmaybe-uninitialized` and `-Wuninitialized` and the undefined behavior sanitizer `fsanitize=undefined` doesn't work either after deleting the config file line and checking the runtime. I don't know what is going on.
Could it be that my compiler does automatically generate inits for all local variables?

**Comment by nikp123** [comment]
It's not, the thing is that the variable gets set earlier by read_args and hence it's modified, therefore the warning doesn't appear.

**Comment by Falcosc** [comment]
> 
> 
> It's not, the thing is that the variable gets set earlier by read_args and hence it's modified, therefore the warning doesn't appear.

If you don't use `-ag` and if you don't have the allow_gateway line in the config and if you remove the `m.allow_gateway_s = NULL;` statement.
Then it does not get set and that is how I tested it. Or did I miss a hidden place where it gets set?

**Comment by Falcosc** [comment]
Here an example branch which does not show any warnings:
https://github.com/Falcosc/wake-on-arp/commit/a9fdf6f7fa74afae55624f4397c90f8644b9f5b2

**Pull request merged**
